### ISSUE TITLE
Website title displays "libpast" instead of "libpasta"

### ISSUE THREAD

**Issue by boustrophedon** [libpasta/libpasta-hugo#4]
https://screenshots.firefox.com/DdaLpqHp1o2bPbje/libpasta.github.io

Firefox 59 on linux.

**Comment by samscott89** [comment]
Hey, thanks for reporting this. I'm guessing it's something to do with fonts, since I have the same setup as you but haven't seen this behaviour (or on any other platform).
Very strange. I'll see what I can do.

**Comment by boustrophedon** [comment]
It might also have something to do with the way this span is calculated or drawn. https://imgur.com/Wy4l99Y

**Comment by samscott89** [comment]
Ah okay, nice observation. Some issue with the underlying theme I think. Will have a play.

**Comment by samscott89** [comment]
Ah it's the SVG generation of the "logo" doing something weird. Okay, should be able to fix it easily enough

**Comment by samscott89** [comment]
Ok, hopefully that has solved it? Let me know if it looks okay on your end.

Thanks again for reporting this. Probably wouldn't have noticed it for a while!

**Comment by boustrophedon** [comment]
it's getting better! https://screenshots.firefox.com/5SOvtegdU8zzxZIG/libpasta.github.io

It looks like the a#logo element is too small? I can confirm that it looks fine in chromium, and the font does seem different (maybe smaller) so it could be related to that.
https://imgur.com/a/L83iaz0

**Comment by boustrophedon** [comment]
The computed font-family for both is just "sans-serif", but I don't know how to check what that font actually is in firefox and chrome.

**Comment by samscott89** [comment]
Ok, how about now? I converted it to a path instead of text! If this doesn't work, I'm just going to give up and convert it into a png...

**Comment by boustrophedon** [comment]
We did it! https://screenshots.firefox.com/jeQ7dtdQpJ264asj/libpasta.github.io

I don't understand fully why it's an svg but yeah, if you want it to be "a logo" and look consistent, a path is probably better than text.
